### ISSUE TITLE
eslint怎么集成到parcel里面去

### ISSUE THREAD

**Issue by liuchang567** [ThaddeusJiang/parcel-react-starter#4]
eslint怎么集成到parcel里面去，我在自己的项目里面使用，发现我的js比如no-var了，都没有提示

**Comment by ThaddeusJiang** [comment]
@yamateH-ch eslint 和 parcel 没有任何关系，也不需要集成。

你使用什么 editor？VSCode 吗？你有安装 eslint 插件吗？
[![Screenshot from Gyazo](https://gyazo.com/f96f3e8f90cb6e8c280ab36bc30091b0/raw)](https://gyazo.com/f96f3e8f90cb6e8c280ab36bc30091b0)

**Comment by liuchang567** [comment]
有的，但是我是想在项目里面用，毕竟vscode不是每个人都用的，现在我用了"parcel-plugin-eslint这个插件才出现提示，
之前 我的做法是，
packjson
"scripts": {
    "dev": "parcel index.html -p 3001",
    "lint": "eslint --ext .js --ext .jsx src",
    "lint-fix": "eslint --fix --ext .js --fix --ext .jsx src"
  }，
在配置eslint.js和balellrc
这样是不行的，搞不明白那里出错了
